language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.8 TORNADO==4.0
  - DJANGO=1.8 TORNADO==4.1

install:
  - pip install Django==$DJANGO tornado==$TORNADO colorlog

script: bash runtests.sh
