language: python

python:
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.8 TORNADO==4.0
  - DJANGO=1.8 TORNADO==4.1

install:
  - pip install Django==$DJANGO tornado==$TORNADO colorlog coveralls

script: bash runtests.sh

after_success: coveralls
